sudo: required
services:
  - docker

jobs:
  include:
#     - stage: Build Docker Image
#       script:
#       - docker build -t sirasaoa/build-android .

    # - stage: Build Debug
    #   script:
    #   - chmod +x gradlew
    #   - docker run -it -e CI=true -v "$PWD":/app sirasaoa/build-android ./gradlew clean assembleDebug

    #   after_success:
    #   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #   - docker push sirasaoa/build-android
            
    - stage: Deploy Release Archive
      script:
      - chmod +x gradlew
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - docker run -it -e CI=true -v "$PWD":/app sirasaoa/build-android ./gradlew clean assembleRelease
      - cp ./app/build/outputs/apk/release/*.apk .

      #Deploy apk to GitHub Releases
      before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "YOUR GIT USER NAME"
      - git config --local user.email "YOUR GIT USER EMAIL"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG

      deploy:
        provider: releases
        token: $GITHUB_API_KEY
        file: "*.apk"
        skip_cleanup: true
        on:
          all_branches: true
